- _layouts/home_layout.html
- accessing-claims-data.md
- tutorial-postman-swagger.md
**JIRA Tickets:**
[AB2D-4151](https://jira.cms.gov/browse/AB2D-4151) - Fix found typos on the website
Github was spelled incorrectly and one of the contracts was incorrect due to a copy and paste issue.
> Fix typos in the website

- .github/CODEOWNERS
**JIRA Tickets:**
[AB2D-4143](https://jira.cms.gov/browse/AB2D-4143) - Add Codeowners
* Automatically request reviews on all PRs
> Feature/ab2d-4143 Add Codeowners

- README.md
update the readme with setup instructions
Unticketed
Updates the readme.md with setup instructions and instructions for running the website locally.
These changes were done to make improve the readme, making it more clear how to setup and run the project locally.
N/A - This is just a readme update, there are no functional updates to the project. I edited the readme directly on github and committed to a new branch.
> [AB2D] Update README.md with setup instructions

- about.md
- access-production-claims-data.md
- api-documentation.md
- index.md
- query-parameters-V2.md
- support.md
https://jira.cms.gov/browse/AB2D-6415
Do-ASAP tickets - https://app.mural.co/t/nava4113/m/nava4113/1729517055266/a47009e194a0baa19fdb2cb09300950b08e0d935
Iterating based on usability testing
> Ab2d 6415 iterate content usability feedback

- _data/api-docs-nav.yml
- _data/footer-links.yml
- _includes/header.html
- access-production-claims-data.md
- access-test-claims-data.md
- api-documentation.md
- filter-claims-data-V2.md
- filter-claims-data-v1.md
- get-a-bearer-token.md
- index.md
- troubleshooting-guide.md
https://jira.cms.gov/browse/...
> 6441 123steps

- _data/api-docs-nav.yml
- _data/footer-links.yml
- _data/nav-primary.yml
- access-production-claims-data.md
- access-sandbox-data.md
- api-documentation.md
- filter-claims-data-V2.md
- filter-claims-data-v1.md
- get-a-bearer-token.md
- mtm-white-paper.md
- production-access.md
- troubleshooting-guide.md
https://jira.cms.gov/browse/AB2D-6450
> Ab2d 6450 internal content recommendations intros

- index.md
https://jira.cms.gov/browse/AB2D-6446
> Update index.md per 6446

- access-production-claims-data.md
- access-sandbox-data.md
- get-a-bearer-token.md
https://jira.cms.gov/browse/AB2D-6440
> Ab2d 6440 update docs compressed files

- .gitignore
- _includes/head.html
- ab2d-data.md
- about.md
- access-production-claims-data.md
- access-sandbox-data.md
- api-documentation.md
- claims-data-details.md
- filter-claims-data-V2.md
- filter-claims-data-v1.md
- get-a-bearer-token.md
- index.md
- mtm-white-paper.md
- production-access.md
- query-parameters-V2.md
- setup-instructions.md
- status.md
- support.md
- troubleshooting-guide.md
- use-cases.md
https://jira.cms.gov/browse/AB2D-6324
Adds descriptions to pages to improve SEO and accessibility
Improved accessibility
Manual QA
> [AB2D-6323] Adds page descriptions

- _includes/header.html
This might be overkill as a PR, but I don't want to cause any code conflicts
> remove announcements link from header

- access-sandbox-data.md
- get-a-bearer-token.md
https://jira.cms.gov/browse/AB2D-6480
Makes numbered headings consistently use roman numerals
Heading list styles were inconsistent
Manual QA
> [AB2D-6480] fix heading list style

- 404.html
- ab2d-data.md
- about.md
- access-production-claims-data.md
- access-sandbox-data.md
- api-documentation.md
- claims-data-details.md
- filter-claims-data-V2.md
- filter-claims-data-v1.md
- get-a-bearer-token.md
- index.md
- mtm-white-paper.md
- production-access.md
- query-parameters-V2.md
- setup-instructions.md
- sitemap.md
- support.md
- troubleshooting-guide.md
- use-cases.md
https://jira.cms.gov/browse/AB2D-6485
Update meta descriptions for SEO optimization.
> Ab2d 6485 update meta descriptions

- _includes/head.html
- ab2d-data.md
- about.md
- access-production-claims-data.md
- access-sandbox-data.md
- api-documentation.md
- claims-data-details.md
- filter-claims-data-V2.md
- filter-claims-data-v1.md
- get-a-bearer-token.md
- index.md
- kitchen-sink.html
- mtm-white-paper.md
- production-access.md
- query-parameters-V2.md
- setup-instructions.md
- sitemap.md
- status.md
- support.md
- troubleshooting-guide.md
- use-cases.md
https://jira.cms.gov/browse/AB2D-6517
Replace `title` with `page_title`. Add `seo_title`
Allows content editors to specify between seo meta titles and page titles (H1's)
> [AB2D-6517] update meta title

- 404.html
- ab2d-data.md
- about.md
- access-production-claims-data.md
- access-sandbox-data.md
- api-documentation.md
- claims-data-details.md
- filter-claims-data-V2.md
- filter-claims-data-v1.md
- get-a-bearer-token.md
- index.md
- mtm-white-paper.md
- production-access.md
- query-parameters-V2.md
- setup-instructions.md
- sitemap.md
- support.md
- troubleshooting-guide.md
- use-cases.md
Update title tags to optimize SEO and match content master document
> Ab2d update seo title tags

- _data/footer-links.yml
- _pages/privacy-settings.md
https://jira.cms.gov/browse/AB2D-6486
NOTE: The scope of this work is front end only. The feature will not be functional until we have working integration with metrics tools
> Implement privacy settings page

- _data/footer-links.yml
- _includes/footer.html
- _includes/identifier.html
- _pages/ab2d-data.md
- _pages/about.md
- _pages/access-production-claims-data.md
- _pages/access-sandbox-data.md
- _pages/api-documentation.md
- _pages/claims-data-details.md
- _pages/filter-claims-data-v1.md
- _pages/filter-claims-data-v2.md
- _pages/get-a-bearer-token.md
- _pages/production-access.md
- _pages/query-parameters-v2.md
- _pages/setup-instructions.md
- _pages/sitemap.md
- _pages/support.md
- _pages/troubleshooting-guide.md
- _pages/use-cases.md
https://jira.cms.gov/browse/ab2d-6501
> ab2d-6501 Content review

- .github/workflows/deploy-dev.yml
Attempts to fix deploy action on initial PR creation
> Use context sha

- _layouts/api-docs.html
- _layouts/default.html
https://jira.cms.gov/browse/AB2D-6547
Adds overflows to sidebars so they are scrollable if they dont fit in the window
Allows users to scroll sidebars independently of content
Manual QA
> [AB2D-6547] Add sidebar scrolling

- .github/workflows/deploy-dev.yml
Updates the Github Action to always grab the correct commit SHA from the branch HEAD
> Get correct sha

- _data/footer-links.yml
- _pages/claims-data-details.md
- _pages/filter-claims-data-v1.md
- _pages/production-access.md
- _pages/query-parameters-v2.md
- _pages/setup-instructions.md
- _pages/troubleshooting-guide.md
https://jira.cms.gov/browse/...
> ab2d-content-bug-bash

- _pages/access-production-claims-data.md
- _pages/access-sandbox-data.md
Comments out all mention of file compression.
> Comment out content on file compression

- .github/workflows/deploy.yml
- _pages/status.md
n/a
This fixes the API Status indicator on the status page
> Updates and fixes the status page

- _pages/access-production-claims-data.md
- _pages/access-sandbox-data.md
https://jira.cms.gov/browse/AB2D-6662
Adds back content about file compression
Manual QA
> [AB2D-6662] Add back file compression

- _pages/status.md
https://jira.cms.gov/browse/AB2D-6749
Updates the API status to check prod instead of sandbox
n/a
Manual QA
> [AB2D-6749] Updates the API status to check prod instead of sandbox

- .github/workflows/deploy.yml
[PLT-657](https://jira.cms.gov/browse/PLT-657)
references to ab2d-bcda-dpc-platform renamed to cdap
we are renaming the ab2d-bcda-dpc-platform repo to cdap
upon approval, ab2d-bcda-dpc-platform repo will be renamed to cdap and workflow re-ran, if successful PR merged if not ab2d-bcda-dpc-platform repo rename to cdap reverted while investigating why workflow failed
> PLT-657:Rename the public platform github repo

- .github/workflows/a11y-check.yml
- .github/workflows/comment-pr.yml
- .github/workflows/deploy.yml
https://jira.cms.gov/browse/AB2D-6769
Updates the pa11y path to use correct preview URL path
(Background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.)
https://github.com/CMSgov/ab2d-website/actions/runs/16171917060
> [AB2D-6769] Updates the pa11y path to use correct preview URL path

- .github/workflows/deploy.yml
Removes baseurl to create a clean release for prod deployment
> Remove baseurl for release

- .github/workflows/deploy.yml
- .github/workflows/promote.yml
- .github/workflows/release.yml
https://jira.cms.gov/browse/AB2D-6870
Updates promote workflow to work correctly post greenfield
Updates our release workflow with updated credentials
Latest working job: https://github.com/CMSgov/ab2d-website/actions/runs/17109898876
> AB2D-6870 Fix promote workflow

- _includes/head.html
https://jira.cms.gov/browse/AB2D-6872
Fixes tealium script pointing to the wrong site
Manual QA
> AB2D-6872 Fix tealium script

- _pages/support.md
https://jira.cms.gov/browse/AB2D-6861
Remove hyperlink, minimal changes to text copy.
[See thread with BB2 team.
](https://cmsgov.slack.com/archives/C01F4P1N64U/p1756141642205129)
(How were the changes verified? Did you fully test the acceptance criteria in the ticket? Provide reproducible testing instructions and screenshots if applicable.)
> Remove broken site link
